### ISSUE TITLE
Credentials file uses different ENV variable names than official plugin

### ISSUE THREAD

**Issue by mastermargie** [chuckorde/veracode-python#1]
According to the README, the variable names used in the credentials file are `VERACODE_API_ID` and `VERACODE_API_SECRET`. The code from the official veracode_api_signing module uses `VERACODE_API_KEY_ID` and `VERACODE_API_KEY_SECRET`.

Any chance this could be changed so that there is parity between the two?

**Comment by chuckorde** [comment]
Updated in Release v0.1.67
